// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: config/v1/compares.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Script        string                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	BuildScript   string                 `protobuf:"bytes,4,opt,name=build_script,json=buildScript,proto3" json:"build_script,omitempty"`
	RunScript     string                 `protobuf:"bytes,5,opt,name=run_script,json=runScript,proto3" json:"run_script,omitempty"`
	RunName       string                 `protobuf:"bytes,7,opt,name=run_name,json=runName,proto3" json:"run_name,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	FileNames     []string               `protobuf:"bytes,9,rep,name=file_names,json=fileNames,proto3" json:"file_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareResponse) Reset() {
	*x = CompareResponse{}
	mi := &file_config_v1_compares_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareResponse) ProtoMessage() {}

func (x *CompareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_compares_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareResponse.ProtoReflect.Descriptor instead.
func (*CompareResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_compares_proto_rawDescGZIP(), []int{0}
}

func (x *CompareResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompareResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompareResponse) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *CompareResponse) GetBuildScript() string {
	if x != nil {
		return x.BuildScript
	}
	return ""
}

func (x *CompareResponse) GetRunScript() string {
	if x != nil {
		return x.RunScript
	}
	return ""
}

func (x *CompareResponse) GetRunName() string {
	if x != nil {
		return x.RunName
	}
	return ""
}

func (x *CompareResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CompareResponse) GetFileNames() []string {
	if x != nil {
		return x.FileNames
	}
	return nil
}

type GetComparesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compares      []*CompareResponse     `protobuf:"bytes,1,rep,name=compares,proto3" json:"compares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetComparesResponse) Reset() {
	*x = GetComparesResponse{}
	mi := &file_config_v1_compares_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetComparesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComparesResponse) ProtoMessage() {}

func (x *GetComparesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_compares_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComparesResponse.ProtoReflect.Descriptor instead.
func (*GetComparesResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_compares_proto_rawDescGZIP(), []int{1}
}

func (x *GetComparesResponse) GetCompares() []*CompareResponse {
	if x != nil {
		return x.Compares
	}
	return nil
}

type GetCompareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompareRequest) Reset() {
	*x = GetCompareRequest{}
	mi := &file_config_v1_compares_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompareRequest) ProtoMessage() {}

func (x *GetCompareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_compares_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompareRequest.ProtoReflect.Descriptor instead.
func (*GetCompareRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_compares_proto_rawDescGZIP(), []int{2}
}

func (x *GetCompareRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddCompareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Script        string                 `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	BuildScript   string                 `protobuf:"bytes,3,opt,name=build_script,json=buildScript,proto3" json:"build_script,omitempty"`
	RunScript     string                 `protobuf:"bytes,4,opt,name=run_script,json=runScript,proto3" json:"run_script,omitempty"`
	RunName       string                 `protobuf:"bytes,6,opt,name=run_name,json=runName,proto3" json:"run_name,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	FileNames     []string               `protobuf:"bytes,8,rep,name=file_names,json=fileNames,proto3" json:"file_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCompareRequest) Reset() {
	*x = AddCompareRequest{}
	mi := &file_config_v1_compares_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCompareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCompareRequest) ProtoMessage() {}

func (x *AddCompareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_compares_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCompareRequest.ProtoReflect.Descriptor instead.
func (*AddCompareRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_compares_proto_rawDescGZIP(), []int{3}
}

func (x *AddCompareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddCompareRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *AddCompareRequest) GetBuildScript() string {
	if x != nil {
		return x.BuildScript
	}
	return ""
}

func (x *AddCompareRequest) GetRunScript() string {
	if x != nil {
		return x.RunScript
	}
	return ""
}

func (x *AddCompareRequest) GetRunName() string {
	if x != nil {
		return x.RunName
	}
	return ""
}

func (x *AddCompareRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddCompareRequest) GetFileNames() []string {
	if x != nil {
		return x.FileNames
	}
	return nil
}

type UpdateCompareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Script        *string                `protobuf:"bytes,3,opt,name=script,proto3,oneof" json:"script,omitempty"`
	BuildScript   *string                `protobuf:"bytes,4,opt,name=build_script,json=buildScript,proto3,oneof" json:"build_script,omitempty"`
	RunScript     *string                `protobuf:"bytes,5,opt,name=run_script,json=runScript,proto3,oneof" json:"run_script,omitempty"`
	RunName       *string                `protobuf:"bytes,7,opt,name=run_name,json=runName,proto3,oneof" json:"run_name,omitempty"`
	Description   *string                `protobuf:"bytes,8,opt,name=description,proto3,oneof" json:"description,omitempty"`
	FileNames     []string               `protobuf:"bytes,9,rep,name=file_names,json=fileNames,proto3" json:"file_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompareRequest) Reset() {
	*x = UpdateCompareRequest{}
	mi := &file_config_v1_compares_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompareRequest) ProtoMessage() {}

func (x *UpdateCompareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_compares_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompareRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompareRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_compares_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCompareRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCompareRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCompareRequest) GetScript() string {
	if x != nil && x.Script != nil {
		return *x.Script
	}
	return ""
}

func (x *UpdateCompareRequest) GetBuildScript() string {
	if x != nil && x.BuildScript != nil {
		return *x.BuildScript
	}
	return ""
}

func (x *UpdateCompareRequest) GetRunScript() string {
	if x != nil && x.RunScript != nil {
		return *x.RunScript
	}
	return ""
}

func (x *UpdateCompareRequest) GetRunName() string {
	if x != nil && x.RunName != nil {
		return *x.RunName
	}
	return ""
}

func (x *UpdateCompareRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateCompareRequest) GetFileNames() []string {
	if x != nil {
		return x.FileNames
	}
	return nil
}

type DeleteCompareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompareRequest) Reset() {
	*x = DeleteCompareRequest{}
	mi := &file_config_v1_compares_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompareRequest) ProtoMessage() {}

func (x *DeleteCompareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_compares_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompareRequest.ProtoReflect.Descriptor instead.
func (*DeleteCompareRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_compares_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCompareRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_config_v1_compares_proto protoreflect.FileDescriptor

const file_config_v1_compares_proto_rawDesc = "" +
	"\n" +
	"\x18config/v1/compares.proto\x12\tconfig.v1\"\xf1\x01\n" +
	"\x0fCompareResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06script\x18\x03 \x01(\tR\x06script\x12!\n" +
	"\fbuild_script\x18\x04 \x01(\tR\vbuildScript\x12\x1d\n" +
	"\n" +
	"run_script\x18\x05 \x01(\tR\trunScript\x12\x19\n" +
	"\brun_name\x18\a \x01(\tR\arunName\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"file_names\x18\t \x03(\tR\tfileNamesJ\x04\b\x06\x10\a\"M\n" +
	"\x13GetComparesResponse\x126\n" +
	"\bcompares\x18\x01 \x03(\v2\x1a.config.v1.CompareResponseR\bcompares\"#\n" +
	"\x11GetCompareRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe3\x01\n" +
	"\x11AddCompareRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\x12!\n" +
	"\fbuild_script\x18\x03 \x01(\tR\vbuildScript\x12\x1d\n" +
	"\n" +
	"run_script\x18\x04 \x01(\tR\trunScript\x12\x19\n" +
	"\brun_name\x18\x06 \x01(\tR\arunName\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"file_names\x18\b \x03(\tR\tfileNamesJ\x04\b\x05\x10\x06\"\xe5\x02\n" +
	"\x14UpdateCompareRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06script\x18\x03 \x01(\tH\x01R\x06script\x88\x01\x01\x12&\n" +
	"\fbuild_script\x18\x04 \x01(\tH\x02R\vbuildScript\x88\x01\x01\x12\"\n" +
	"\n" +
	"run_script\x18\x05 \x01(\tH\x03R\trunScript\x88\x01\x01\x12\x1e\n" +
	"\brun_name\x18\a \x01(\tH\x04R\arunName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\b \x01(\tH\x05R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"file_names\x18\t \x03(\tR\tfileNamesB\a\n" +
	"\x05_nameB\t\n" +
	"\a_scriptB\x0f\n" +
	"\r_build_scriptB\r\n" +
	"\v_run_scriptB\v\n" +
	"\t_run_nameB\x0e\n" +
	"\f_descriptionJ\x04\b\x06\x10\a\"&\n" +
	"\x14DeleteCompareRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB\x95\x01\n" +
	"\rcom.config.v1B\rComparesProtoP\x01Z0github.com/CSKU-Lab/config-server/grpc/config/v1\xa2\x02\x03CXX\xaa\x02\tConfig.V1\xca\x02\tConfig\\V1\xe2\x02\x15Config\\V1\\GPBMetadata\xea\x02\n" +
	"Config::V1b\x06proto3"

var (
	file_config_v1_compares_proto_rawDescOnce sync.Once
	file_config_v1_compares_proto_rawDescData []byte
)

func file_config_v1_compares_proto_rawDescGZIP() []byte {
	file_config_v1_compares_proto_rawDescOnce.Do(func() {
		file_config_v1_compares_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_compares_proto_rawDesc), len(file_config_v1_compares_proto_rawDesc)))
	})
	return file_config_v1_compares_proto_rawDescData
}

var file_config_v1_compares_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_config_v1_compares_proto_goTypes = []any{
	(*CompareResponse)(nil),      // 0: config.v1.CompareResponse
	(*GetComparesResponse)(nil),  // 1: config.v1.GetComparesResponse
	(*GetCompareRequest)(nil),    // 2: config.v1.GetCompareRequest
	(*AddCompareRequest)(nil),    // 3: config.v1.AddCompareRequest
	(*UpdateCompareRequest)(nil), // 4: config.v1.UpdateCompareRequest
	(*DeleteCompareRequest)(nil), // 5: config.v1.DeleteCompareRequest
}
var file_config_v1_compares_proto_depIdxs = []int32{
	0, // 0: config.v1.GetComparesResponse.compares:type_name -> config.v1.CompareResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_v1_compares_proto_init() }
func file_config_v1_compares_proto_init() {
	if File_config_v1_compares_proto != nil {
		return
	}
	file_config_v1_compares_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_compares_proto_rawDesc), len(file_config_v1_compares_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_v1_compares_proto_goTypes,
		DependencyIndexes: file_config_v1_compares_proto_depIdxs,
		MessageInfos:      file_config_v1_compares_proto_msgTypes,
	}.Build()
	File_config_v1_compares_proto = out.File
	file_config_v1_compares_proto_goTypes = nil
	file_config_v1_compares_proto_depIdxs = nil
}
