name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    uses: CSKU-Lab/.github/.github/workflows/docker-publish.yml@main
    with:
      image_name: config-server
      gitops_paths: apps/config-server/env.libsonnet
      service_name: config-server
    secrets: inherit
